<?php

declare(strict_types=1);

namespace RouteForge\Laravel\Console;

use Illuminate\Console\Command;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\File;
use RouteForge\Laravel\TierResolver;

/**
 * 从路由表生成 TS 类型声明
 * @see .docs/SPEC.md §3.2
 */
class RouteForgeTypesCommand extends Command
{
    protected $signature = 'route:forge:types
        {--level= : 仅生成指定层级下的路由类型}
        {--json : 输出 JSON 对象格式（键为路由名）}
        {--out= : 写入指定文件路径；不传则输出到 stdout}';

    protected $description = '生成 TS 路由类型声明（route:forge:types --level=admin --json --out=src/types/forge-routes.d.ts）';

    private const BODY_METHODS = ['POST', 'PUT', 'PATCH'];

    public function handle(Router $router, TierResolver $resolver): int
    {
        $levels = array_keys(config('forge.levels', []));
        $filterLevel = $this->option('level');

        // level 过滤校验
        if ($filterLevel !== null && $filterLevel !== '' && !in_array($filterLevel, $levels, true)) {
            $this->error("Unknown level: {$filterLevel}");
            $this->line('Available levels: ' . (empty($levels) ? '(none)' : implode(', ', $levels)));
            return 1;
        }

        // 收集路由元信息（含未分配层级路由）
        $routes = [];
        foreach ($router->getRoutes() as $route) {
            $name = $route->getName();
            if ($name === null || $name === '') {
                continue;
            }
            if (str_starts_with($name, 'forge.routes.')) {
                continue;
            }

            $level = $resolver->resolve($route);

            // --level 过滤：仅包含指定层级的路由
            if ($filterLevel !== null && $filterLevel !== '' && $level !== $filterLevel) {
                continue;
            }

            $methods = array_values(array_filter(
                $route->methods(),
                fn ($m) => strtoupper($m) !== 'HEAD'
            ));
            $method = !empty($methods) ? strtoupper($methods[0]) : 'GET';
            $params = $route->parameterNames();
            $hasBody = in_array($method, self::BODY_METHODS, true);

            $routes[$name] = [
                'method' => $method,
                'params' => $params,
                'hasBody' => $hasBody,
                // response 始终为 unknown（v1.0 不支持自定义响应类型）
                'response' => 'unknown',
            ];
        }

        // 输出
        if ($this->option('json')) {
            $output = $this->generateJson($routes);
        } else {
            $output = $this->generateDts($routes);
        }

        $outFile = $this->option('out');
        if ($outFile !== null && $outFile !== '') {
            $dir = dirname($outFile);
            if (!is_dir($dir)) {
                File::makeDirectory($dir, 0755, true);
            }
            File::put($outFile, $output);
            $this->info("Written to: {$outFile}");
            return 0;
        }

        $this->line($output);
        return 0;
    }

    /**
     * 生成 d.ts 内容
     * @param array<string,array{method:string,params:string[],hasBody:bool,response:string}> $routes
     */
    private function generateDts(array $routes): string
    {
        $lines = [];
        $lines[] = '// AUTO-GENERATED by route:forge:types. Do not edit.';
        $lines[] = '// @see .docs/SPEC.md §3.2, §4.2';
        $lines[] = '';
        $lines[] = 'export interface ForgeRoutes {';
        foreach ($routes as $name => $r) {
            $paramsFields = array_map(fn ($p) => "    {$p}: string | number;", $r['params']);
            $paramsBlock = empty($paramsFields) ? 'record {}' : "{\n" . implode("\n", $paramsFields) . "\n  }";
            $lines[] = "  {$this->quoteKey($name)}: {";
            $lines[] = "    method: '{$r['method']}';";
            $lines[] = "    params: {$paramsBlock};";
            if ($r['hasBody']) {
                $lines[] = "    body: unknown;";
            }
            $lines[] = "    response: {$r['response']};";
            $lines[] = "  };";
        }
        $lines[] = '}';
        $lines[] = '';
        return implode("\n", $lines);
    }

    /**
     * 生成 JSON 对象（键为路由名）
     */
    private function generateJson(array $routes): string
    {
        $out = [];
        foreach ($routes as $name => $r) {
            $entry = [
                'method' => $r['method'],
                'params' => $r['params'],
            ];
            if ($r['hasBody']) {
                $entry['body'] = 'unknown';
            }
            $entry['response'] = $r['response'];
            $out[$name] = $entry;
        }
        return json_encode($out, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function quoteKey(string $name): string
    {
        // 仅在含特殊字符时引号
        if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $name)) {
            return $name;
        }
        return json_encode($name);
    }
}
