<?php

declare(strict_types=1);

namespace RouteForge\Laravel\Console;

use Illuminate\Console\Command;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\File;
use RouteForge\Laravel\RouteRepository;
use RouteForge\Laravel\TierResolver;

/**
 * 从路由表生成 TS 类型声明
 *
 * @see .docs/SPEC.md §3.2
 */
class RouteForgeTypesCommand extends Command
{
    protected $signature = 'route:forge:types
        {--level= : 仅生成指定层级下的路由类型}
        {--json : 输出 JSON 对象格式（键为路由名）}
        {--out= : 写入指定文件路径；不传则输出到 stdout}';

    protected $description = '生成 TS 路由类型声明（route:forge:types --level=admin --json --out=src/types/forge-routes.d.ts）';

    private const BODY_METHODS = ['POST', 'PUT', 'PATCH'];

    public function handle(Router $router, TierResolver $resolver): int
    {
        $levels = array_keys(config('forge.levels', []));
        $filterLevel = $this->option('level');

        // level 过滤校验
        if ($filterLevel !== null && $filterLevel !== '' && !in_array($filterLevel, $levels,
                true)) {
            $this->error("Unknown level: {$filterLevel}");
            $this->line('Available levels: ' . (empty($levels) ? '(none)' : implode(', ',
                    $levels)));
            return 1;
        }

        // 收集路由元信息（按层级分组）
        $routesByLevel = [];
        foreach ($router->getRoutes() as $route) {
            $name = $route->getName();
            if ($name === null || $name === '') {
                continue;
            }
            if (RouteRepository::isExcludedRouteName($name)) {
                continue;
            }

            $level = $resolver->resolve($route);

            // unassigned 路由不生成类型（SPEC §3.2：无层级归属，不进入 ForgeRoutes 映射）
            if ($level === null) {
                continue;
            }

            // --level 过滤：仅包含指定层级的路由
            if ($filterLevel !== null && $filterLevel !== '' && $level !== $filterLevel) {
                continue;
            }

            $methods = array_values(array_filter(
                $route->methods(),
                fn($m) => strtoupper($m) !== 'HEAD',
            ));
            $method  = !empty($methods) ? strtoupper($methods[0]) : 'GET';
            $params  = $route->parameterNames();
            $hasBody = in_array($method, self::BODY_METHODS, true);

            // 从 URI 模板提取 URL 可选参数（{param?} 语法）
            $optionalParams = $this->extractOptionalParams($route->uri());

            $routesByLevel[$level][$name] = [
                'method'  => $method,
                'params'  => $params,
                'optionalParams' => $optionalParams,
                'defaults'       => $route->defaults,
                'hasBody' => $hasBody,
                // response 始终为 unknown（v1.0 不支持自定义响应类型）
                'response' => 'unknown',
            ];
        }

        // 输出
        if ($this->option('json')) {
            $output = $this->generateJson($routesByLevel);
        } else {
            $output = $this->generateDts($routesByLevel);
        }

        $outFile = $this->option('out');
        if ($outFile !== null && $outFile !== '') {
            $dir = dirname($outFile);
            if (!is_dir($dir)) {
                File::makeDirectory($dir, 0755, true);
            }
            File::put($outFile, $output);
            $this->info("Written to: {$outFile}");
            return 0;
        }

        $this->line($output);
        return 0;
    }

    /**
     * 生成 d.ts 内容（二级映射：层级 → 路由名 → 类型约束）
     *
     * 生成的 ForgeRouteMap 同时通过 module augmentation 增强 @route-forge/core 的同名接口，
     * 使前端 composable（useForge / useForgeApi）自动获得路由名和参数的类型推断。
     *
     * @param array<string,array<string,array{method:string,params:string[],optionalParams:string[],defaults:array<string,mixed>,hasBody:bool,response:string}>> $routesByLevel
     */
    private function generateDts(array $routesByLevel): string
    {
        $timestamp = date('Y-m-d\TH:i:s.000\Z');
        $levels = array_map(fn($l) => $l === '' ? 'unassigned' : $l, array_keys($routesByLevel));

        $lines      = [];
        $lines[]    = '// AUTO-GENERATED by route:forge:types. Do not edit.';
        $lines[]    = "// 生成时间: {$timestamp}";
        $lines[]    = '// 端点: /_forge/routes';
        $lines[] = 'import { ForgeRouteMap } from "@route-forge/core";';
        $lines[]    = '';
        $lines[]    = '// ─── 层级名联合类型 ───────────────────────────────────────────';
        $levelUnion = empty($levels) ? 'never' : implode(' | ',
            array_map(fn($l) => "'{$l}'", $levels));
        $lines[]    = "export type ForgeLevel = {$levelUnion};";
        $lines[]    = '';
        $lines[]    = '// ─── 各层级路由名联合类型 ─────────────────────────────────────';
        $lines[] = 'export type ForgeRouteName<L extends ForgeLevel> = L extends keyof ForgeRouteMap';
        $lines[] = '  ? keyof ForgeRouteMap[L] & string';
        $lines[]    = '  : never;';
        $lines[]    = '';
        $lines[] = '// ─── 单条路由元信息（端点返回的 routes 值结构） ────────────────────';
        $lines[] = 'export interface ForgeRouteMeta {';
        $lines[] = '  method: string;';
        $lines[] = '  uri: string;';
        $lines[] = '  parameters: string[];';
        $lines[] = '  parameter_defaults: Record<string, unknown>;';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = '// ─── 按层级 → 路由名 → 类型约束的映射 ────────────────────────';
        $lines[] = '// 通过 module augmentation 增强 @route-forge/core 的 ForgeRouteMap，';
        $lines[] = '// 使 useForge / useForgeApi 自动获得路由名和参数的类型推断。';
        $lines[] = '// ⚠ 依赖 @route-forge/core 包，请确保前端项目已安装该依赖。';
        $lines[]    = '';
        $lines[] = "declare module '@route-forge/core' {";
        $lines[] = '  interface ForgeRouteMap {';

        foreach ($routesByLevel as $level => $routes) {
            $levelKey = $level ?: 'unassigned';
            $lines[]  = "    {$this->quoteKey($levelKey)}: {";
            foreach ($routes as $name => $r) {
                $paramsFields = $this->formatParamsFields($r['params'], $r['optionalParams'],
                    '        ');
                $paramsBlock  = empty($paramsFields)
                    ? '{}'
                    : "{\n" . implode("\n", $paramsFields) . "\n      }";
                $lines[]      = "      {$this->quoteKey($name)}: {";
                $lines[]      = "        method: '{$r['method']}';";
                $lines[]      = "        params: {$paramsBlock};";
                if ($r['hasBody']) {
                    $lines[] = "        body: unknown;";
                }
                $lines[] = "        response: {$r['response']};";
                $lines[] = "      };";
            }
            $lines[] = '    };';
            $lines[] = '';
        }

        $lines[] = '  }';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = '// ─── 本地别名（向后兼容） ──────────────────────────────────────';
        $lines[] = 'export type ForgeRoutes = ForgeRouteMap;';
        $lines[] = '';
        $lines[] = '// ─── 工具类型：从 ForgeRouteMap 提取具体字段 ────────────────────';
        $lines[]    = '';
        $lines[]    = '/** 提取指定层级 + 路由名的 method */';
        $lines[]    = 'export type ForgeMethod<';
        $lines[]    = '  L extends ForgeLevel,';
        $lines[]    = '  N extends ForgeRouteName<L>,';
        $lines[] = '> = L extends keyof ForgeRouteMap';
        $lines[] = "  ? N extends keyof ForgeRouteMap[L] ? ForgeRouteMap[L][N]['method'] : never";
        $lines[] = '  : never;';
        $lines[]    = '';
        $lines[]    = '/** 提取指定层级 + 路由名的路径参数 */';
        $lines[]    = 'export type ForgeParams<';
        $lines[]    = '  L extends ForgeLevel,';
        $lines[]    = '  N extends ForgeRouteName<L>,';
        $lines[] = '> = L extends keyof ForgeRouteMap';
        $lines[] = "  ? N extends keyof ForgeRouteMap[L] ? ForgeRouteMap[L][N]['params'] : never";
        $lines[] = '  : never;';
        $lines[]    = '';
        $lines[]    = '/** 提取指定层级 + 路由名的 body 类型（GET/DELETE 为 never） */';
        $lines[]    = 'export type ForgeBody<';
        $lines[]    = '  L extends ForgeLevel,';
        $lines[]    = '  N extends ForgeRouteName<L>,';
        $lines[] = '> = L extends keyof ForgeRouteMap';
        $lines[] = '  ? N extends keyof ForgeRouteMap[L]';
        $lines[] = "    ? 'body' extends keyof ForgeRouteMap[L][N]";
        $lines[] = "      ? ForgeRouteMap[L][N]['body']";
        $lines[] = '      : never';
        $lines[]    = '    : never';
        $lines[]    = '  : never;';
        $lines[]    = '';
        $lines[]    = '/** 提取指定层级 + 路由名的 response 类型 */';
        $lines[]    = 'export type ForgeResponse<';
        $lines[]    = '  L extends ForgeLevel,';
        $lines[]    = '  N extends ForgeRouteName<L>,';
        $lines[] = '> = L extends keyof ForgeRouteMap';
        $lines[] = "  ? N extends keyof ForgeRouteMap[L] ? ForgeRouteMap[L][N]['response'] : never";
        $lines[] = '  : never;';
        $lines[]    = '';

        return implode("\n", $lines);
    }

    /**
     * 生成 JSON 对象（二级结构：层级 → 路由名）
     */
    private function generateJson(array $routesByLevel): string
    {
        $out = [];
        foreach ($routesByLevel as $level => $routes) {
            $levelData = [];
            foreach ($routes as $name => $r) {
                $entry = [
                    'method' => $r['method'],
                    'params' => $r['params'],
                ];
                if (!empty($r['defaults'])) {
                    $entry['parameter_defaults'] = (object)$r['defaults'];
                }
                if ($r['hasBody']) {
                    $entry['body'] = 'unknown';
                }
                $entry['response'] = $r['response'];
                $levelData[$name]  = $entry;
            }
            $out[$level ?: 'unassigned'] = $levelData;
        }
        return json_encode($out, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function quoteKey(string $name): string
    {
        // 仅在含特殊字符时引号
        if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $name)) {
            return $name;
        }
        return json_encode($name);
    }

    /**
     * 格式化 params 字段列表
     *
     * TS 类型的 ? 标记基于 URL 模板中参数是否可选（{param?} 语法），
     * 而非是否有默认值。默认值通过 parameter_defaults 独立返回。
     *
     * @param string[] $params
     * @param string[] $optionalParams URL 中可选的参数名列表（{param?} 语法）
     * @param string   $indent
     *
     * @return string[]
     */
    private function formatParamsFields(array $params, array $optionalParams, string $indent): array
    {
        return array_map(function ($p) use ($optionalParams, $indent) {
            $optional = in_array($p, $optionalParams, true) ? '?' : '';
            return "{$indent}{$p}{$optional}: string | number;";
        }, $params);
    }

    /**
     * 从 URI 模板中提取可选参数名（{param?} 语法）
     *
     * @return string[]
     */
    private function extractOptionalParams(string $uri): array
    {
        preg_match_all('/\{(\w+)\?\}/', $uri, $matches);
        return $matches[1] ?? [];
    }
}